#!/bin/bash

echo "==================================================================="
echo "QUICK DEPLOY - Service Physics LMS"
echo "==================================================================="
echo ""
echo "Step 1: Create GitHub Repository"
echo "-----------------------------------"
echo "Go to: https://github.com/new"
echo "Name: service-physics-lms"
echo "Click 'Create repository'"
echo ""
echo "Step 2: Push to GitHub"
echo "----------------------"
echo "Run these commands:"
echo ""
echo "cd /Users/tim/Desktop/Onboarding/service-physics-lms"
echo "git remote add origin https://github.com/timwcash/service-physics-lms.git"
echo "git push -u origin main"
echo ""
echo "Step 3: Deploy to Vercel"
echo "------------------------"
echo "1. Go to: https://vercel.com"
echo "2. Sign in with GitHub"
echo "3. Import 'service-physics-lms' repository"
echo "4. Click Deploy (no env vars needed for demo mode)"
echo ""
echo "You'll get a URL like: https://service-physics-lms.vercel.app"
echo ""
echo "==================================================================="
